### ISSUE TITLE
No longer support media embed with WP4

### ISSUE THREAD

**Issue by alepee** [neyre/sir-trevor-wp#4]
SirTrevor fail to get media ID after uploading, and cause Javascript to crash on WP4.

> Error from sir-trevor-wp.js:42
`Uncaught TypeError: Cannot read property 'substr' of undefined`

`imgid` cannot be defined

**Comment by neyre** [comment]
Should be fixed in a8350bdc4ffdeeb35b7763faa20dd77db4ab4023

**Comment by alepee** [comment]
Thanks @neyre
